=== JLffeguor/cours-gestion-2012-maxime-jerome/trunk/WineCaveSwing/document/data.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pays >
<!ELEMENT regionV> 
<!ELEMENT ss_region>

<!ATTLIST pays
	nom CDATA #REQUIRED
	continent CDATA #IMPLIED
	devise CDATA #IMPLIED>

<!ATTLIST regionV
	nom CDATA #REQUIRED
	nom_pays CDATA #REQUIRED>	

<!ATTLIST ss_region
	nom CDATA #REQUIRED
	region CDATA #REQUIRED>

=== JLffeguor/cours-gestion-2012-maxime-jerome/trunk/WineCaveSwing/document/regionV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE regionV SYSTEM  "data.dtd">

<regionV nom="Alsace"nom_pays="france"/>
<regionV nom="Beaujolais"nom_pays="france"/>
<regionV nom="Bordeaux"nom_pays="france"/>
<regionV nom="Bourgogne"nom_pays="france"/>
<regionV nom="Bugey"nom_pays="france"/>
<regionV nom="Champagne"nom_pays="france"/>
<regionV nom="Corse"nom_pays="france"/>
<regionV nom="Jura"nom_pays="france"/>
<regionV nom="Languedoc-Roussillon"nom_pays="france"/>
<regionV nom="Loire"nom_pays="france"/>
<regionV nom="Lorraine"nom_pays="france"/>
<regionV nom="Poitou-Charentes"nom_pays="france"/>
<regionV nom="Provence"nom_pays="france"/>
<regionV nom="RhÃ´ne"nom_pays="france"/>
<regionV nom="Savoie"nom_pays="france"/>
<regionV nom="Sud-Ouest"nom_pays="france"/>
<regionV nom="Vin de Table"nom_pays="france"/>
<regionV nom="Vins de Pays"nom_pays="france"/>
