=== JLffeguor/cours-gestion-2012-maxime-jerome/WineCaveSwing/document/data.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pays >
<!ELEMENT regionV> 
<!ELEMENT ss_regionV>
<!ELEMENT categorie>
<!ELEMENT couleur>
<!ELEMENT classement>

<!ATTLIST pays
	nom CDATA #REQUIRED
	continent CDATA #IMPLIED
	devise CDATA #IMPLIED
	isInDB CDATA #REQUIRED>

<!ATTLIST regionV
	nom CDATA #REQUIRED
	nom_pays CDATA #REQUIRED
	isInDB CDATA #REQUIRED>	

<!ATTLIST ss_regionV
	nom CDATA #REQUIRED
	region CDATA #REQUIRED
	isInDB CDATA #REQUIRED>

<!ATTLIST categorie
	nom CDATA #REQUIRED>
	
<!ATTLIST couleur
	nom_bouteille CDATA #REQUIRED
	capaciteLitre CDATA #REQUIRED>

<!ATTLIST classment
	nom CDATA #REQUIRED>

=== JLffeguor/cours-gestion-2012-maxime-jerome/trunk/WineCaveSwing/document/ss_regionV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ss_regionV SYSTEM "data.dtd">

<ss_regionV nom="Alsace" region ="Alsace"/>
<ss_regionV nom="Alsace Grands Crus" region ="Alsace"/>
<ss_regionV nom="Crémant-d'Alsace" region ="Alsace"/>
<ss_regionV nom="Beaujolais" region ="Beaujolais"/>
<ss_regionV nom="Beaujolais Supérieur" region ="Beaujolais"/>
<ss_regionV nom="Beaujolais Village" region ="Beaujolais"/>
<ss_regionV nom="Brouilly" region ="Beaujolais"/>
<ss_regionV nom="Chénas" region ="Beaujolais"/>
<ss_regionV nom="Chiroubles" region ="Beaujolais"/>
<ss_regionV nom="Coteaux-du-Lyonnais" region ="Beaujolais"/>
<ss_regionV nom="Côtes-de-Brouilly" region ="Beaujolais"/>
<ss_regionV nom="Fleurie" region ="Beaujolais"/>
<ss_regionV nom="Juliénas" region ="Beaujolais"/>
<ss_regionV nom="Morgon" region ="Beaujolais"/>
<ss_regionV nom="Moulin-à-vent" region ="Beaujolais"/>
<ss_regionV nom="Régnié" region ="Beaujolais"/>
<ss_regionV nom="Saint-Amour" region ="Beaujolais"/>
<ss_regionV nom="Blancs Liquoreux" region ="Bordeaux"/>
<ss_regionV nom="Blayais et Bourgeais" region ="Bordeaux"/>
<ss_regionV nom="Bordeaux" region ="Bordeaux"/>
<ss_regionV nom="Bordeaux Clairet" region ="Bordeaux"/>
<ss_regionV nom="Bordeaux Supérieur" region ="Bordeaux"/>
<ss_regionV nom="Cotes de Bordeaux" region ="Bordeaux"/>
<ss_regionV nom="Crémant-de-Bordeaux" region ="Bordeaux"/>
<ss_regionV nom="Dordogne et Garonne" region ="Bordeaux"/>
<ss_regionV nom="Graves" region ="Bordeaux"/>
<ss_regionV nom="Libournais" region ="Bordeaux"/>
<ss_regionV nom="Médoc" region ="Bordeaux"/>
<ss_regionV nom="Aligoté" region ="Bourgogne"/>
<ss_regionV nom="Bourgogne" region ="Bourgogne"/>
<ss_regionV nom="Bourgogne Côtes du Couchois" region ="Bourgogne"/>
<ss_regionV nom="Chablisien" region ="Bourgogne"/>
<ss_regionV nom="Chitry" region ="Bourgogne"/>
<ss_regionV nom="Côte Chalonnaise" region ="Bourgogne"/>
<ss_regionV nom="Côte de Beaune" region ="Bourgogne"/>
<ss_regionV nom="Côte de Nuits" region ="Bourgogne"/>
<ss_regionV nom="Côte-de-nuits-villages" region ="Bourgogne"/>
<ss_regionV nom="Coteaux Bourguignons" region ="Bourgogne"/>
<ss_regionV nom="Coulanges-la-Vineuse" region ="Bourgogne"/>
<ss_regionV nom="Crémant-de-Bourgogne" region ="Bourgogne"/>
<ss_regionV nom="Epineuil" region ="Bourgogne"/>
<ss_regionV nom="Hautes-côtes-de-beaune" region ="Bourgogne"/>
<ss_regionV nom="Hautes-côtes-de-nuits" region ="Bourgogne"/>
<ss_regionV nom="Irancy" region ="Bourgogne"/>
<ss_regionV nom="Mâconnais" region ="Bourgogne"/>
<ss_regionV nom="Passe-tout-grains" region ="Bourgogne"/>
<ss_regionV nom="Saint-Bris" region ="Bourgogne"/>
<ss_regionV nom="Tonnerre" region ="Bourgogne"/>
<ss_regionV nom="Vézelay" region ="Bourgogne"/>
<ss_regionV nom="Champagne" region ="Champagne"/>
<ss_regionV nom="Côteaux-Champenois" region ="Champagne"/>
<ss_regionV nom="Rosé-des-Riceys" region ="Champagne"/>
<ss_regionV nom="Ajaccio" region ="Corse"/>
<ss_regionV nom="Muscat-du-Cap-Corse" region ="Corse"/>
<ss_regionV nom="Patrimonio" region ="Corse"/>
<ss_regionV nom="Vins-de-corse" region ="Corse"/>
<ss_regionV nom="Arbois" region ="Jura"/>
<ss_regionV nom="Arbois-Pupillin" region ="Jura"/>
<ss_regionV nom="Château-Chalon" region ="Jura"/>
<ss_regionV nom="Côtes-du-Jura" region ="Jura"/>
<ss_regionV nom="Crémant du Jura" region ="Jura"/>
<ss_regionV nom="L'étoile" region ="Jura"/>
<ss_regionV nom="Macvin du Jura" region ="Jura"/>
<ss_regionV nom="Languedoc" region ="Languedoc-Roussillon"/>
<ss_regionV nom="Roussillon" region ="Languedoc-Roussillon"/>
<ss_regionV nom="Anjou" region ="Loire"/>
<ss_regionV nom="Crémant-de-loire" region ="Loire"/>
<ss_regionV nom="Région du Centre" region ="Loire"/>
<ss_regionV nom="Région Nantaise" region ="Loire"/>
<ss_regionV nom="Région Touraine" region ="Loire"/>
<ss_regionV nom="Rosé-de-loire" region ="Loire"/>
<ss_regionV nom="Saumur" region ="Loire"/>
<ss_regionV nom="Côtes-de-toul" region ="Lorraine"/>
<ss_regionV nom="Moselle" region ="Lorraine"/>
<ss_regionV nom="Haut-poitou" region ="Poitou-Charentes"/>
<ss_regionV nom="Pineau-des-charentes" region ="Poitou-Charentes"/>
<ss_regionV nom="Bandol" region ="Provence"/>
<ss_regionV nom="Bellet" region ="Provence"/>
<ss_regionV nom="Cassis" region ="Provence"/>
<ss_regionV nom="Coteaux-d'aix-en-provence" region ="Provence"/>
<ss_regionV nom="Coteaux-varois-en-provence" region ="Provence"/>
<ss_regionV nom="Côtes-de-provence" region ="Provence"/>
<ss_regionV nom="Les baux-de-provence" region ="Provence"/>
<ss_regionV nom="Palette" region ="Provence"/>
<ss_regionV nom="Beaumes-de-venise" region ="Rhône"/>
<ss_regionV nom="Châtillon-en-diois" region ="Rhône"/>
<ss_regionV nom="Clairette-de-bellegarde" region ="Rhône"/>
<ss_regionV nom="Clairette-de-Die" region ="Rhône"/>
<ss_regionV nom="Costières-de-Nîmes" region ="Rhône"/>
<ss_regionV nom="Coteaux-de-pierrevert" region ="Rhône"/>
<ss_regionV nom="Côteaux-du-Tricastin" region ="Rhône"/>
<ss_regionV nom="Côtes-du-luberon" region ="Rhône"/>
<ss_regionV nom="Côtes-du-Rhône" region ="Rhône"/>
<ss_regionV nom="Côtes-du-Rhône-Villages" region ="Rhône"/>
<ss_regionV nom="Côtes-du-ventoux" region ="Rhône"/>
<ss_regionV nom="Côtes-du-vivarais" region ="Rhône"/>
<ss_regionV nom="Crémant-de-die" region ="Rhône"/>
<ss_regionV nom="Grignan-les-Adhémar" region ="Rhône"/>
<ss_regionV nom="Muscat de Beaumes-de-Venise" region ="Rhône"/>
<ss_regionV nom="Rasteau" region ="Rhône"/>
<ss_regionV nom="Rhône Méridional" region ="Rhône"/>
<ss_regionV nom="Rhône Septentrional" region ="Rhône"/>
<ss_regionV nom="Crépy" region ="Savoie"/>
<ss_regionV nom="Roussette-de-savoie" region ="Savoie"/>
<ss_regionV nom="Roussette-du-Bugey" region ="Savoie"/>
<ss_regionV nom="Seyssel" region ="Savoie"/>
<ss_regionV nom="Vin-de-savoie" region ="Savoie"/>
<ss_regionV nom="Béarn" region ="Sud-Ouest"/>
<ss_regionV nom="Bergerac" region ="Sud-Ouest"/>
<ss_regionV nom="Buzet" region ="Sud-Ouest"/>
<ss_regionV nom="Cahors" region ="Sud-Ouest"/>
<ss_regionV nom="Coteaux-du-quercy" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-de-bergerac" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-de-duras" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-de-millau" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-de-Montravel" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-de-saint-mont" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-du-brulhois" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-du-frontonnais" region ="Sud-Ouest"/>
<ss_regionV nom="Côtes-du-marmandais" region ="Sud-Ouest"/>
<ss_regionV nom="Entraygues-le-fel" region ="Sud-Ouest"/>
<ss_regionV nom="Floc-de-gascogne" region ="Sud-Ouest"/>
<ss_regionV nom="Fronton" region ="Sud-Ouest"/>
<ss_regionV nom="Gaillac" region ="Sud-Ouest"/>
<ss_regionV nom="Haut-Montravel" region ="Sud-Ouest"/>
<ss_regionV nom="Irouleguy" region ="Sud-Ouest"/>
<ss_regionV nom="Jurançon" region ="Sud-Ouest"/>
<ss_regionV nom="Jurançon Sec" region ="Sud-Ouest"/>
<ss_regionV nom="Lavilledieu" region ="Sud-Ouest"/>
<ss_regionV nom="Madiran" region ="Sud-Ouest"/>
<ss_regionV nom="Marcillac" region ="Sud-Ouest"/>
<ss_regionV nom="Monbazillac" region ="Sud-Ouest"/>
<ss_regionV nom="Montravel" region ="Sud-Ouest"/>
<ss_regionV nom="Pacherenc-du-vic-bilh" region ="Sud-Ouest"/>
<ss_regionV nom="Pécharmant" region ="Sud-Ouest"/>
<ss_regionV nom="Rosette" region ="Sud-Ouest"/>
<ss_regionV nom="Saussignac" region ="Sud-Ouest"/>
<ss_regionV nom="Tursan" region ="Sud-Ouest"/>
<ss_regionV nom="Vins-d'estaing" region ="Sud-Ouest"/>
<ss_regionV nom="VdP Cathare" region ="Vins de Pays"/>
<ss_regionV nom="VdP Charentais" region ="Vins de Pays"/>
<ss_regionV nom="VdP Coteaux Charitois" region ="Vins de Pays"/>
<ss_regionV nom="VdP Côteaux d'Enserune" region ="Vins de Pays"/>
<ss_regionV nom="VdP Coteaux de Fontcaude" region ="Vins de Pays"/>
<ss_regionV nom="VdP Coteaux de Murviel" region ="Vins de Pays"/>
<ss_regionV nom="VdP Coteaux et terrasses de Montauban" region ="Vins de Pays"/>
<ss_regionV nom="VdP Côtes de Lastours" region ="Vins de Pays"/>
<ss_regionV nom="VdP d'Allobrogie" region ="Vins de Pays"/>
<ss_regionV nom="VdP d'Ariège" region ="Vins de Pays"/>
<ss_regionV nom="VdP d'Hauterive" region ="Vins de Pays"/>
<ss_regionV nom="VdP d'Oc" region ="Vins de Pays"/>
<ss_regionV nom="VdP d'Oleron" region ="Vins de Pays"/>
<ss_regionV nom="VdP d'Orange" region ="Vins de Pays"/>
<ss_regionV nom="VdP d'Urfé" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Cassan" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Caux" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Cessenon" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Franche-Comté" region ="Vins de Pays"/>
<ss_regionV nom="VdP de l'Ardèche" region ="Vins de Pays"/>
<ss_regionV nom="VdP de l'Aude" region ="Vins de Pays"/>
<ss_regionV nom="VdP de l'Hérault" region ="Vins de Pays"/>
<ss_regionV nom="VdP de l'Ile de Beauté" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Bénovie" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Cité de Carcassonne" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la côte Vermeille" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Drôme" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Haute Vallée de l'Aude" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Haute Vallée de l'Orb" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Sainte-Baume" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Vallée du Paradis" region ="Vins de Pays"/>
<ss_regionV nom="VdP de la Vienne" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Lot" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Méditerranée" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Saint Guilhem le Désert" region ="Vins de Pays"/>
<ss_regionV nom="VdP de Saint-Sardos" region ="Vins de Pays"/>
